export const COMPOSER_MAKE_QUERY_REQUEST = "COMPOSER_MAKE_QUERY_REQUEST";
export const COMPOSER_MAKE_MUTATION_REQUEST = "COMPOSER_MAKE_MUTATION_REQUEST";
export const COMPOSER_GET_QUERY_RESPONSE = "COMPOSER_GET_QUERY_RESPONSE";
export const COMPOSER_GET_MUTATION_RESPONSE = "COMPOSER_GET_MUTATION_RESPONSE";
export const SET_PAGE_LOAD_PROGRESS = "SET_PAGE_LOAD_PROGRESS";
export const SET_ROUTE_DATAS = "SET_ROUTE_DATAS";
export const SET_QUERY_DATAS = "SET_QUERY_DATAS";
