export const COMPOSER_SEND_REQUEST_HEADER_CMD =
  "COMPOSER_SEND_REQUEST_HEADER_CMD";
export const COMPOSER_SET_REQUEST_HEADER = "COMPOSER_SET_REQUEST_HEADER";
export const COMPOSER_SEND_RESPONSE_TO_MIDDLEWARE =
  "COMPOSER_SEND_RESPONSE_TO_MIDDLEWARE";
export const SET_PAGE_LOAD_PROGRESS = "SET_PAGE_LOAD_PROGRESS";
export const SET_ROUTE_DATAS = "SET_ROUTE_DATAS";
export const SET_QUERY_DATAS = "SET_QUERY_DATAS";
