export const COMPOSER_MAKE_QUERY_REQUEST = "COMPOSER_MAKE_QUERY_REQUEST";
export const COMPOSER_MAKE_MUTATION_REQUEST = "COMPOSER_MAKE_MUTATION_REQUEST";
export const COMPOSER_GET_QUERY_RESPONSE = "COMPOSER_GET_QUERY_RESPONSE";
export const COMPOSER_GET_MUTATION_RESPONSE = "COMPOSER_GET_MUTATION_RESPONSE";
